Repository mojira/arisa-kt, pull requests merged in 2020-04, with the labels that each got.

#27 fix CHK processing unconfirmed tickets
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/modules/CHKModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/CHKModuleTest.kt
Labels: bug

#28 fix getting Mojang Priority
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
Labels: bug

#42 Fix piracy signatures using whitespaces not working
  src/main/kotlin/io/github/mojira/arisa/modules/PiracyModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/PiracyModuleTest.kt
Labels: bug

#45 Make tag removal comment change more meaningful
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/RemoveTriagedMeqsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/RemoveTriagedMeqsModuleTest.kt
Labels: enhancement

#44 add cache
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
Labels: enhancement

#46 Added keep private module
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt
Labels: enhancement, module

#39 add confirmation module
  .gitignore
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
  src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationTest.kt
Labels: enhancement, module

#48 Remove shadow mode
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Labels: enhancement

#49 Making messages more in line with helper messages
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Labels: enhancement

#64 Fix #62
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationTest.kt
Labels: bug

#92 store last run to file
  .gitignore
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Cache.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Labels: enhancement

#91 Fix #86
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
Labels: enhancement

#99 add duplicates to json config
  arisa.json
Labels: bug

#108 Iterate over all issues
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
Labels: HIGHPRIORITY, bug

#107 add linked module
  arisa.json
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
Labels: enhancement, module

#121 Add Italian to the language module config
  arisa.json
Labels: bug

#124 Fix #109
  arisa.json
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Labels: bug

#125 ModuleRegistry
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
Labels: enhancement

#137 Change author name rquirements for HideImpostors
  src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsTest.kt
Labels: bug

#136 Fix HideImpostors failing when envoking the restrict comment method
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
Labels: bug

#143 Feature/dont reopen after staff edit
  arisa.json
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
Labels: enhancement

#149 Allow Modules to see isues that have been resolved or reopened as last action.
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/modules/EmptyModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
  src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/EmptyModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
Labels: enhancement

#152 Optimize API calls
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationTest.kt
Labels: enhancement

#154 Add TransferVersionModule
  arisa.json
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsTest.kt
Labels: enhancement, module

#162 Fix TransferVersionModule attempting to add versions from a different project
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsTest.kt
Labels: bug

#163 Only rerun failed tickets after a restart
  src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Cache.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/QueryCache.kt
Labels: enhancement

#167 Require status "Open" or "Reopened" for parents in TransferVersions
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
  src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsTest.kt
Labels: bug

#172 Feature/131
  arisa.json
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
Labels: enhancement

#171 Feature/transfer dupes
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
  src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
  src/main/kotlin/io/github/mojira/arisa/modules/AbstractTransferFieldModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
  src/main/kotlin/io/github/mojira/arisa/modules/TransferLinksModule.kt
  src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/ResolveTrashModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/TransferLinksModuleTest.kt
  src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt
Labels: enhancement, module

#173 Fix Arisa searching issues caused by extra '}' in jql string
  src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
Labels: bug

#174 Also consider changes caused by removed links in UpdateLinkedModule
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
  src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt
  src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
Labels: bug

#175 Fix arisa trying to add versions in transfer versions that are already added
  src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
Labels: bug

#177 Add missing config for transfer links module
  arisa.json
Labels: bug
